name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - uses: actions/checkout@v3
      - name: Install UV
        run: |
          pip install uv
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: make install-${{ matrix.service }}
      - name: Run lint
        run: make lint-${{ matrix.service }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - uses: actions/checkout@v3
      - name: Install UV
        run: |
          pip install uv
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: make install-${{ matrix.service }}
      - name: Run tests
        run: make test-${{ matrix.service }}
