name: CI

on: [push, pull_request]

jobs:
    setup:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [frontend, backend]

        steps:
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Create virtual environment
              run: |
                  python -m venv .venv

    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [frontend, backend]

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Run lint for ${{ matrix.service }}
              run: |
                  make lint SERVICE=${{ matrix.service }}

    test:
        needs: lint
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [frontend, backend]

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Run tests for ${{ matrix.service }}
              run: |
                  make test SERVICE=${{ matrix.service }}
